from .import views
from django.urls import path

from .views import course, course_detail, usercertificate, checkout, payment, \
    payment_success, payment_failure, complete_course, generate_certificate, add_coursematerials, \
    download_course_material, Course_materilals_view, download_pdf_CM

urlpatterns = [

    path('', views.demo, name='demo'),
    path('LOGIN/', views.LOGIN, name='LOGIN'),
    path('REGISTRATION/', views.REGISTRATION, name='REGISTRATION'),
    path('REGISTRATION-mentor/', views.mentor_registration, name='mentor_registration'),
    path('company_registration/', views.company_registration, name='company_registration'),
    path('user_reg/', views.user_reg, name='user_reg'),
    path('mentor_dashboard/', views.mentor_dashboard, name='mentor_dashboard'),
    path('doubts/', views.doubts, name='doubts'),
    path('Home_mentor/', views.Home_mentor, name='Home_mentor'),
    path('login', views.login, name='login'),
    path('company_login', views.company_login, name='company_login'),
    path('mentor_login', views.mentor_login, name='mentor_login'),
    path('logout', views.logout, name='logout'),
    path('home1/', views.home1, name='home1'),
    path('Home/', views.Home, name='Home'),
    path('courses_mentor', views.courses_mentor, name='courses_mentor'),
    path('about2/', views.about2, name='about2'),
    path('userprofile/', views.userprofile, name='userprofile'),
    path('activity/', views.activity, name='activity'),
    path('Messages/', views.Messages, name='Messages'),
    path('course-details/<slug:slug>/enroll_course/', views.enroll_course, name='enroll_course'),
    path('course/', views.course, name='course'),
    path('quiz_answer/<int:course_id>/', views.quiz_answer, name='quiz_answer'),
    path('course-details/<slug:course_slug>/', views.course_details, name='course_details'),
    path('course-detail/<slug:course_slug>/', views.course_detail, name='course_detail'),
    path('courses/', views.courses, name='courses'),
    path('reports/', views.reports, name='reports'),
    path('changepassword/', views.changepassword, name='changepassword'),
    path('add_cart/<int:id>/', views.add_cart, name='add_cart'),
    path('view_cart/',views.view_cart,name='view_cart'),
    path('de_cart/<int:id>/',views.de_cart,name='de_cart'),
    path('profile/', views.profile, name='profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-profilementor/', views.update_profilementor, name='update_profilementor'),
    path('checkout/<int:id>/',views.checkout,name='checkout'),
    path('review/', views.Review, name='Review'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('search/',views.search_course,name='search_course'),
    path('payments/', views.payments, name='payments'),
    path('certificate/', views.certificate, name='certificate'),
    path('job-list/', views.job_list, name='job_list'),
    path('job-add/', views.Job_add, name='Job_add'),
    path('job_details/<int:id>/', views.job_details, name='job_details'),
    path('job_apply/', views.job_apply, name='job_apply'),
    path('job_index/', views.job_index, name='job_index'),
    path('company_adminpanel/', views.company_adminpanel, name='company_adminpanel'),
    path('Learner_dashboard/', views.Learner_dashboard, name='Learner_dashboard'),
    path('forms/', views.forms, name='forms'),
    path('my-url/', views.my_view, name='my_view'),
    path('Add_quiz/', views.Add_quiz, name='Add_quiz'),
    path('Quiz_view/', views.Quiz_view, name='Quiz_view'),

    path('course-details/watch_course/<slug:slug>', views.watch_course, name='watch_course'),
    path('error/', views.error, name='error'),
    path('LearnmateEdu/<int:id>/', views.payment, name='LearnmateEdu'),
    path('LearnmateEdu-success/', views.payment_success, name='LearnmateEdu-success'),
    path('LearnmateEdu-failure/', views.payment_failure, name='payment_failure'),
    path('generate_certificate/<int:id>/', generate_certificate, name='generate_certificate'),
    path('courses/<int:id>/complete/', complete_course, name='complete_course'),
    path('add_coursematerials/', add_coursematerials, name='add_coursematerials'),
    path('Course_materilals_view/<int:id>/', Course_materilals_view, name='Course_materilals_view'),
    path('download_pdf_CM/<int:id>', download_pdf_CM, name='download_pdf_CM'),
    path('download_pdf_Certificate/<int:id>', download_pdf_CM, name='download_pdf_Certificate'),

]

