# Generated by Django 4.1.1 on 2022-10-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearnapp', '0002_freecourses_javaadva_javaintro_paidcourses_pyadva_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='javaadva',
        ),
        migrations.DeleteModel(
            name='javaintro',
        ),
        migrations.DeleteModel(
            name='paidcourses',
        ),
        migrations.DeleteModel(
            name='pyadva',
        ),
        migrations.RemoveField(
            model_name='pyintro',
            name='name',
        ),
        migrations.DeleteModel(
            name='user_log',
        ),
        migrations.DeleteModel(
            name='user_reg',
        ),
        migrations.DeleteModel(
            name='freecourses',
        ),
        migrations.DeleteModel(
            name='pyintro',
        ),
    ]
