# Generated by Django 4.1.1 on 2022-10-14 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elearnapp', '0003_delete_javaadva_delete_javaintro_delete_paidcourses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='freecourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(max_length=30)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='javaadva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('video', models.FileField(default=0, upload_to='videos')),
                ('duration', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
                ('students', models.CharField(max_length=30)),
                ('outcomes', models.CharField(max_length=300)),
                ('curriculum', models.CharField(max_length=300)),
                ('mentor', models.CharField(max_length=50)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='javaintro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('video', models.FileField(upload_to='videos')),
                ('duration', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
                ('students', models.CharField(max_length=20)),
                ('outcomes', models.CharField(max_length=300)),
                ('curriculum', models.CharField(max_length=300)),
                ('mentor', models.CharField(max_length=50)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='paidcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=200)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='pyadva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('video', models.FileField(upload_to='videos')),
                ('duration', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
                ('students', models.CharField(max_length=20)),
                ('outcomes', models.CharField(max_length=300)),
                ('curriculum', models.CharField(max_length=300)),
                ('mentor', models.CharField(max_length=50)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField(max_length=30)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='pyintro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('duration', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
                ('students', models.CharField(max_length=20)),
                ('outcomes', models.CharField(max_length=300)),
                ('curriculum', models.CharField(max_length=300)),
                ('mentor', models.CharField(max_length=50)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearnapp.freecourses')),
            ],
        ),
    ]
