# Generated by Django 4.1.1 on 2023-05-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearnapp', '0003_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
