# Generated by Django 4.1.1 on 2023-05-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearnapp', '0004_alter_quiz_answer_alter_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='coursename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
