# Generated by Django 4.1.1 on 2022-10-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearnapp', '0005_alter_pyintro_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyintro',
            name='duration',
            field=models.TimeField(),
        ),
    ]
