# Generated by Django 4.1.1 on 2022-10-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearnapp', '0006_alter_pyintro_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyintro',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
