# Generated by Django 4.1.1 on 2023-05-11 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LearnmateEdu.course', unique=True)),
                ('question', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
