# Generated by Django 4.1.1 on 2023-05-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0002_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quiz_save',
        ),
    ]
