# Generated by Django 4.1.1 on 2023-05-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0003_rename_quiz_quiz_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/coursematerials/')),
            ],
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LearnmateEdu.course'),
        ),
    ]
