# Generated by Django 4.1.1 on 2023-05-15 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0004_course_material_alter_coursematerial_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentor_log',
            fields=[
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField(max_length=30)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
