# Generated by Django 4.1.1 on 2023-05-16 05:16

from django.db import migrations, models
import django.db.models.deletion
import oscrypto._ffi


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0005_mentor_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(default=oscrypto._ffi.null, max_length=50)),
                ('applicant_email', models.EmailField(default=oscrypto._ffi.null, max_length=30)),
                ('resume', models.FileField(default=oscrypto._ffi.null, upload_to='media/resumes/')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LearnmateEdu.job')),
            ],
        ),
    ]
