# Generated by Django 4.1.1 on 2023-05-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oscrypto._ffi


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0007_alter_apply_job_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(default=oscrypto._ffi.null, upload_to='resumes'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnmateEdu.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
