# Generated by Django 4.1.1 on 2023-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0008_alter_apply_job_resume_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_save',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='quiz_save',
            old_name='question',
            new_name='answer2',
        ),
        migrations.AddField(
            model_name='quiz_save',
            name='answer3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz_save',
            name='answer4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz_save',
            name='question1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz_save',
            name='question2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz_save',
            name='question3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz_save',
            name='question4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
