# Generated by Django 4.1.1 on 2023-05-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0009_rename_answer_quiz_save_answer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=255, null=True)),
                ('answer1', models.CharField(max_length=255, null=True)),
                ('question2', models.CharField(max_length=255, null=True)),
                ('answer2', models.CharField(max_length=255, null=True)),
                ('question3', models.CharField(max_length=255, null=True)),
                ('answer3', models.CharField(max_length=255, null=True)),
                ('question4', models.CharField(max_length=255, null=True)),
                ('answer4', models.CharField(max_length=255, null=True)),
                ('course_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LearnmateEdu.course', unique=True)),
            ],
        ),
    ]
