# Generated by Django 4.1.1 on 2023-05-16 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnmateEdu', '0010_save_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=255, null=True)),
                ('answer1', models.CharField(max_length=255, null=True)),
                ('question2', models.CharField(max_length=255, null=True)),
                ('answer2', models.CharField(max_length=255, null=True)),
                ('question3', models.CharField(max_length=255, null=True)),
                ('answer3', models.CharField(max_length=255, null=True)),
                ('question4', models.CharField(max_length=255, null=True)),
                ('answer4', models.CharField(max_length=255, null=True)),
                ('course', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='LearnmateEdu.course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnmateEdu.table_quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
